### ISSUE TITLE
Problems of groups grading

### ISSUE THREAD

**Issue by phunlh2001** [Kunniii/edn_auto_ext#1]
The scoring feature for group grades in your extension can be applied to slots that are not assigned to me. So, this functionality exceeds the capabilities of EduNext and may result in score inaccuracies, causing potential errors.

**Comment by Kunniii** [comment]
I think it's a feature. Enjoy using **feature** since the BackEnd doesn't do any checking and 100% trust the data sent via API.

It's a good show case for what **NOT** to do when developing an API :D

**Comment by Kunniii** [comment]
Just kidding, I will start working on this **BUG** thing. Thanks for inform me :D
