### ISSUE TITLE
Feature: add stars for the UIs

### ISSUE THREAD

**Issue by phunlh2001** [Kunniii/edn_auto_ext#5]
I think you should add a 5 stars interface set for the UI tab. 👍 

Because when I press "grade" -> my brain always reminds me "Check the stars of my teammates, please" 😆

**Comment by Kunniii** [comment]
# 🤔🤔
Bruh, but if we all vote for everyone's maximum stars possible, then adding a new Star UI seems to be redundant. 😟

**Comment by Kunniii** [comment]
I will collect more info if users want stars UI or not! Thanks for the idea.

**Comment by Kunniii** [comment]
I will code this issue! No need to fix.

**Comment by Kunniii** [comment]
I don't think we need this feature since it would make the UI a bit complicated.
