### ISSUE TITLE
Error: Grade Comment

### ISSUE THREAD

**Issue by thangtnx** [Kunniii/edn_auto_ext#7]
the grade comment function didn't work as expected and it gave an error in the console like this
![image](https://github.com/Kunniii/edn_auto_ext/assets/71863631/49626f50-aba0-4cbf-8abd-9f4402e800c0)

**Comment by Kunniii** [comment]
Look like the response data is not in the same format as I expected, they must be changed how the data is returned.

Hotfix released! v2.2.5
